language: c
addons:
  apt:
    packages:
    - ruby-dev
    - gcc
    - make
    - rpm
before_install:
- gem install fpm
deploy:
  provider: releases
  api_key:
    secure: Oz6jtSSZl4iJOC47FY5WQofOS86eP6drpSR4GiGzeWmkkSBGFRypvscqDwgo0S/5FxozZ69YekvM1eWnm8AAL3pZGO8rW4t9JtD5TsYEcgbOw/zwg0B7fvp8tNf+w6+9/wJaIZEpHB5Vez0/X2oqN1f9GnTTrxXH2LnNwwr94IsI0CW/38slZphGLR3UDue2Fdn0q44hNuHriJDwsg1MfqkMEgU7Qcelgt83yYRnCd8Ngr/1tYaJcAn4cJVQIPZQpiCB5fXZFlOzSCiuYmTmr07EsusCPEu/dA0ZGwY4NTjozR6psKMV3MA3b/zbVO31WjfeaU2RNQT5ekfc9dEDIVDc1rebh1MCpR8KtKFcsyQs8oPFfF7zb52oasokbw+RHjngiJHn+zafgZVhfFDjTbCbhd+rtl4eCSG4bsk1SR1SdEdIN8hq/fH020aku1D/hGDbeYjHEN9RqJPcc4bo8RVJ8IFprRhoW6IjcD8teboxmWKod2aUlXvbmtELi2AncPQ3HH9NYkBo50OtFjeOTw3bRBowrxzXHPt56l4nkmbzFO+ViCC1a8hvxsYB9esc2fDXVbVLS3oXcZwqYAQI2GpCUQFsUxUPGk653pVaQ5354Ik8Au72oITVZlZ5a51A5IcxMeO0Fambj2iOR4JToYDkyeiE64JKVrjgiQkR52A=
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    tags: true
